### ISSUE TITLE
Valid rules are skipped due to selector errors

### ISSUE THREAD

**Issue by waterplea** [danielroe/beasties#79]
Transferring this issue here, because it seems to still be present:
https://github.com/GoogleChromeLabs/critters/issues/153

My issue is this valid code:
```css
:-webkit-any(a, button, select, textarea, input, label) {
  ...
}
```

Causes `rules skipped due to selector errors`, even though selector is valid and it's the only way to use `:is(...)` for Safari 13 and below.

**Comment by JeanMeche** [comment]
Repro: https://stackblitz.com/edit/vitejs-vite-oy4xyate?file=src%2Fmain.ts&terminal=dev

I noticed error due to pseudo selectors following a child combinator. 

```css  
.table > .foo > * {  color:red; }
```

Is parsed correctly, while 

```css
  .table > :not(.foo) > * {  color:red; }
```

Throws `.table >  > * -> Did not expect successive traversals.`
